# Generated by Django 4.2.10 on 2024-02-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('publish', 'Publish'), ('draft', 'Draft')], default='publish', max_length=16, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('publish', 'Publish'), ('draft', 'Draft')], default='publish', max_length=16, verbose_name='status'),
        ),
    ]
