# Generated by Django 4.2.10 on 2024-02-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_category_status_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordinal',
            field=models.IntegerField(default=0, verbose_name='ordinal'),
        ),
        migrations.AddField(
            model_name='product',
            name='ordinal',
            field=models.IntegerField(default=0, verbose_name='ordinal'),
        ),
    ]
