# Generated by Django 4.2.10 on 2024-02-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_category_ordinal_product_ordinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
