# Generated by Django 4.2.10 on 2024-02-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_category_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
