# Generated by Django 4.2.10 on 2024-02-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='ordinal',
            field=models.IntegerField(default=0, help_text='ordinal = 0 sẽ là ảnh to nhất'),
        ),
    ]
