COMMON_STATUS_COMPLETED = "completed"
COMMON_STATUS_PUBLISH = "publish"
COMMON_STATUS_DRAFT = "draft"
COMMON_STATUS_CHOICES = (
    (COMMON_STATUS_COMPLETED, "Completed"),
    (COMMON_STATUS_PUBLISH, "Publish"),
    (COMMON_STATUS_DRAFT, "Draft"),
)
